// This file was generated by WTL Dialog wizard 
// CommonOptForm.cpp : Implementation of CCommonOptForm

#include "stdafx.h"
#include "CommonOptForm.h"
#include "../RegArchive.h"

extern LPCTSTR g_MainDlgName;
extern LPCTSTR RegPath;

// CCommonOptForm
CCommonOptForm::CCommonOptForm() : m_bSavePreviousPane(false), m_eWTLVersion(eWTL75)
{
}

CCommonOptForm::~CCommonOptForm()
{
}

void CCommonOptForm::SaveOptions()
{
	DoDataExchange(TRUE);
	CComboBox ComboVersion = GetDlgItem(IDC_COMBO_WTLVERSION);
	m_eWTLVersion = (eWTLVersion)ComboVersion.GetCurSel();
	_AtlModule.m_eWTLVersion = m_eWTLVersion;

	CRegArchive RegArchive;
	if (RegArchive.Open(HKEY_CURRENT_USER, RegPath, true))
	{
		SaveSettings(RegArchive, g_MainDlgName);
		RegArchive.Close();
	}
}

LRESULT CCommonOptForm::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	CRegArchive RegArchive;
	if (RegArchive.Open(HKEY_CURRENT_USER, RegPath))
	{
		LoadSettings(RegArchive, g_MainDlgName);
		RegArchive.Close();
	}
	CComboBox ComboVersion = GetDlgItem(IDC_COMBO_WTLVERSION);
	ComboVersion.AddString(_T("WTL 7.1"));
	ComboVersion.AddString(_T("WTL 7.5"));
	ComboVersion.SetCurSel(m_eWTLVersion);

	DoDataExchange();
	return 1;  // Let the system set the focus
}
