////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2004 Sergey Solozhentsev
// Author: 	Sergey Solozhentsev e-mail: salos@mail.ru
// Product:	WTL Helper
// File:      	DDXoptForm.cpp
// Created:	21.12.2004 10:46
// 
//   Using this software in commercial applications requires an author
// permission. The permission will be granted to everyone excluding the cases
// when someone simply tries to resell the code.
//   This file may be redistributed by any means PROVIDING it is not sold for
// profit without the authors written consent, and providing that this notice
// and the authors name is included.
//   This file is provided "as is" with no expressed or implied warranty. The
// author accepts no liability if it causes any damage to you or your computer
// whatsoever.
//
////////////////////////////////////////////////////////////////////////////////

// This file was generated by WTL Dialog wizard 
// DDXoptForm.cpp : Implementation of CDDXoptForm

#include "stdafx.h"
#include "DDXoptForm.h"
#include ".\ddxoptform.h"
#include "../RegArchive.h"

extern LPCTSTR RegPath;
extern LPCTSTR DDXRegName;
// CDDXoptForm
CDDXoptForm::CDDXoptForm() : m_Protection(0), m_bOnlyDlgs(true), m_bUseTypePrefix(true)
{
}

CDDXoptForm::~CDDXoptForm()
{
}

LRESULT CDDXoptForm::OnInitDialog(HWND hwndFocus, LPARAM lParam)
{
	CRegArchive RegArchive;
	if(RegArchive.Open(HKEY_CURRENT_USER, RegPath))
	{
		LoadSettings(RegArchive, DDXRegName);
		RegArchive.Close();
	}
	DoDataExchange();
	return TRUE;
}

void CDDXoptForm::SaveOptions()
{
	DoDataExchange(TRUE);
	CRegArchive RegArchive;
	if (RegArchive.Open(HKEY_CURRENT_USER, RegPath, true))
	{
		SaveSettings(RegArchive, DDXRegName);
		RegArchive.Close();
	}
}