////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2004 Sergey Solozhentsev
// Author: 	Sergey Solozhentsev e-mail: salos@mail.ru
// Product:	WTL Helper
// File:      	FunctionOptDlg.h
// Created:	21.12.2004 10:46
// 
//   Using this software in commercial applications requires an author
// permission. The permission will be granted to everyone excluding the cases
// when someone simply tries to resell the code.
//   This file may be redistributed by any means PROVIDING it is not sold for
// profit without the authors written consent, and providing that this notice
// and the authors name is included.
//   This file is provided "as is" with no expressed or implied warranty. The
// author accepts no liability if it causes any damage to you or your computer
// whatsoever.
//
////////////////////////////////////////////////////////////////////////////////

// This file was generated by WTL Dialog wizard 
// FunctionOptDlg.h : Declaration of the CFunctionOptDlg

#pragma once

#include <atlcrack.h>
// CFunctionOptDlg
#include "../Dialog/ColorSetupDlg.h"

class CFunctionOptDlg : 
	public CDialogImpl<CFunctionOptDlg>,
	public CWinDataExchange<CFunctionOptDlg>,
	public CSettings<CFunctionOptDlg>
{
	CColorSetupDlg m_ColorSetup;
public:
	BOOL m_bInline;
	BOOL m_Sort;
	BOOL m_bNewStyle;
	BOOL m_bUseAtlMisc;
	BOOL m_bAllowDlgIdle;
	BOOL m_bCheckMissingEndMap;
public:
	CFunctionOptDlg();
	~CFunctionOptDlg();
	enum { IDD = IDD_FUNCTIONOPTDLG };

	void SaveOptions();
    BEGIN_MSG_MAP(CFunctionOptDlg)
		MSG_WM_INITDIALOG(OnInitDialog)
		COMMAND_HANDLER(IDC_BUTTON_COLORS, BN_CLICKED, OnColorsClicked)
    END_MSG_MAP()

	BEGIN_DDX_MAP(CFunctionOptDlg)
		DDX_CHECK(IDC_CHECK_INLINE, m_bInline)
		DDX_CHECK(IDC_CHECK_SORT, m_Sort)
		DDX_CHECK(IDC_CHECK_STYLE, m_bNewStyle)
		DDX_CHECK(IDC_CHECK_ATLMISC, m_bUseAtlMisc)
		DDX_CHECK(IDC_CHECK_ALLOW_DIALOAG_IDLE, m_bAllowDlgIdle)
		DDX_CHECK(IDC_CHECK_MISS_END_MAP, m_bCheckMissingEndMap)
	END_DDX_MAP()

	BEGIN_SETTINGS_MAP()
		SETTINGS_VARIABLE_OPT(m_bNewStyle)
		SETTINGS_VARIABLE_OPT(m_Sort)
		SETTINGS_VARIABLE_OPT(m_bInline);
		SETTINGS_VARIABLE_OPT(m_bUseAtlMisc)
		SETTINGS_VARIABLE_OPT(m_bAllowDlgIdle)
		SETTINGS_VARIABLE_OPT(m_bCheckMissingEndMap)
	END_SETTINGS_MAP()

    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnCreate(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnInitDialog(HWND hwndFocus, LPARAM lParam);
	LRESULT OnColorsClicked(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
};


