////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2005 Sergey Solozhentsev
// Author: 	Sergey Solozhentsev e-mail: salos@mail.ru
// Product:	WTL Helper
// File:      	AddSpecFuncDlg.h
// Created:	09.06.2005 11:03
// 
//   Using this software in commercial applications requires an author
// permission. The permission will be granted to everyone excluding the cases
// when someone simply tries to resell the code.
//   This file may be redistributed by any means PROVIDING it is not sold for
// profit without the authors written consent, and providing that this notice
// and the authors name is included.
//   This file is provided "as is" with no expressed or implied warranty. The
// author accepts no liability if it causes any damage to you or your computer
// whatsoever.
//
////////////////////////////////////////////////////////////////////////////////

// This file was generated by WTL Dialog wizard 
// AddSpecFuncDlg.h : Declaration of the CAddSpecFuncDlg

#pragma once

#include "../resource.h"       // main symbols
#include <atlddx.h>

// CAddSpecFuncDlg

class CAddSpecFuncDlg : 
	public CDialogImpl<CAddSpecFuncDlg>,
	public CWinDataExchange<CAddSpecFuncDlg>
{
public:
	CAddSpecFuncDlg();
	~CAddSpecFuncDlg();
	enum { IDD = IDD_ADDSPECFUNCDLG };

	bool m_bCreate;
	bool m_bDestroy;
	bool m_bEnableCreate;
	bool m_bEnableDestroy;
	bool m_bAddCreate;
	bool m_bRemoveDestroy;
	CString m_Title;
	bool m_bDialog;

    BEGIN_MSG_MAP(CAddSpecFuncDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		COMMAND_HANDLER(IDC_CHECK_CREATE, BN_CLICKED, OnBnClickCreate)
		COMMAND_HANDLER(IDC_CHECK_DESTROY, BN_CLICKED, OnBnClickDestroy)
    END_MSG_MAP()

	BEGIN_DDX_MAP(CAddSpecFuncDlg)
		DDX_CHECK(IDC_CHECK_CREATE, m_bCreate)
		DDX_CHECK(IDC_CHECK_DESTROY, m_bDestroy)
		DDX_CHECK(IDC_CHECK_ADD_CREATE, m_bAddCreate)
		DDX_CHECK(IDC_CHECK_REMOVE_DESTROY, m_bRemoveDestroy)
	END_DDX_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnBnClickCreate(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnBnClickDestroy(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
};


