// This file was generated by WTL Dialog wizard 
// ReflectionDlg.h : Declaration of the CReflectionDlg

#pragma once

#include "../resource.h"       // main symbols
#include <atlddx.h>
// CReflectionDlg

#define RD_MESSAGE	1
#define RD_COMMAND	2
#define RD_NOTIFY	4

#define RD_ID		8
#define RD_RANGE	16
#define RD_CODE		32
#define RD_WND		64

class CReflectionDlg : 
	public CDialogImpl<CReflectionDlg>,
	public CWinDataExchange<CReflectionDlg>	
{
	void GetDataFromControls();
public:
	CReflectionDlg();
	~CReflectionDlg();
	enum { IDD = IDD_REFLECTIONDLG };

	CAtlArray<CString> m_CommandIds;
	CAtlArray<CString> m_NotifyIds;
	CAtlArray<CString> m_CommandCodes;
	CAtlArray<CString> m_NotifyCodes;

	static CAtlArray<CString> m_sReflectMessages;
	// in / out parameter 
	// defines which variables are valid
	DWORD m_dwFlags;

	CString m_ID;
	CString m_Range;
	CString m_Code;
	CString m_Wnd;
	CString m_Message;

    BEGIN_MSG_MAP(CReflectionDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		COMMAND_HANDLER(IDC_COMBO_REFLECTTYPE, CBN_SELCHANGE, OnReflectTypeCbnSelchange)
		COMMAND_HANDLER(IDC_CHECK_RANGE, BN_CLICKED, OnRangeBnClick)
		COMMAND_HANDLER(IDC_CHECK_ID, BN_CLICKED, OnIdBnClick)
		COMMAND_HANDLER(IDC_CHECK_CODE, BN_CLICKED, OnCodeBnClicked)
		COMMAND_HANDLER(IDC_CHECK_WINDOW, BN_CLICKED, OnWindowBnCkicked)
    END_MSG_MAP()

    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

	LRESULT OnReflectTypeCbnSelchange(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnRangeBnClick(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnIdBnClick(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnCodeBnClicked(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnWindowBnCkicked(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
};
