////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2004 Sergey Solozhentsev
// Author: 	Sergey Solozhentsev e-mail: salos@mail.ru
// Product:	WTL Helper
// File:      	DDXoptForm.h
// Created:	21.12.2004 10:46
// 
//   Using this software in commercial applications requires an author
// permission. The permission will be granted to everyone excluding the cases
// when someone simply tries to resell the code.
//   This file may be redistributed by any means PROVIDING it is not sold for
// profit without the authors written consent, and providing that this notice
// and the authors name is included.
//   This file is provided "as is" with no expressed or implied warranty. The
// author accepts no liability if it causes any damage to you or your computer
// whatsoever.
//
////////////////////////////////////////////////////////////////////////////////

// This file was generated by WTL Dialog wizard 
// DDXoptForm.h : Declaration of the CDDXoptForm

#pragma once

#include <atlcrack.h>
#include "../resource.h"

// CDDXoptForm

class CDDXoptForm : 
	public CDialogImpl<CDDXoptForm>,
	public CWinDataExchange<CDDXoptForm>,
	public CSettings<CDDXoptForm>
{
public:
	int m_Protection;
	bool m_bOnlyDlgs;
	bool m_bUseTypePrefix;
public:
	CDDXoptForm();
	~CDDXoptForm();
	enum { IDD = IDD_DDXOPTFORM };
	void SaveOptions();

    BEGIN_MSG_MAP(CDDXoptForm)
		MSG_WM_INITDIALOG(OnInitDialog)
    END_MSG_MAP()
	
	BEGIN_SETTINGS_MAP()
		SETTINGS_VARIABLE_OPT(m_Protection)
		SETTINGS_VARIABLE_OPT(m_bOnlyDlgs)
		SETTINGS_VARIABLE_OPT(m_bUseTypePrefix)
	END_SETTINGS_MAP()

	BEGIN_DDX_MAP(CDDXoptForm)
		DDX_RADIO(IDC_RADIO_PUBLIC, m_Protection)
		DDX_CHECK(IDC_CHECK_ONLYDLG, m_bOnlyDlgs)
		DDX_CHECK(IDC_CHECK_PREFIX, m_bUseTypePrefix)
	END_DDX_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);

	LRESULT OnInitDialog(HWND hwndFocus, LPARAM lParam);
};


