//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AddIn.rc
//
#define IDS_PROJNAME                    100
#define IDR_ADDIN                       101
#define IDD_FUNCTIONOPTDLG              101
#define IDS_DEPENDENCES                 101
#define IDD_DDXOPTFORM                  102
#define IDS_COLOR_DEFAULT               102
#define IDD_VARIABLEPAGE                103
#define IDS_TOOLTIP_MESSAGES            103
#define IDS_TOOLTIP_HANDLERS            104
#define IDD_DDXVARIABLE                 105
#define IDS_TOOLTIP_FUNCTIONS           105
#define IDD_TYPECSTRINGDLG              106
#define IDS_TOOLTIP_IDS                 106
#define IDD_ABOUTDLG                    107
#define IDS_SIMPLE_REFLECT              107
#define IDD_WTLHELPERDLG                108
#define IDS_TOOLTIP_REFLECT_NOTIFICATIONS 108
#define IDD_ADDALTMAPDLG                109
#define IDS_TOOLTIP_FORWARD_NOTIFICATIONS 109
#define IDS_TOOLTIP_REFLECT_NOTIFICATIONS_EX 110
#define IDD_COLORSETUPDLG               111
#define IDS_TOOLTIP_DEFAULT_HANDLER     111
#define IDD_COMMONOPTFORM               112
#define IDS_STRING_SPEC_FUNC_DESC       112
#define IDS_STRING_SPEC_CHECK_ADD_CREATE 113
#define IDD_REFLECTIONDLG               114
#define IDS_STRING_SPEC_CHECK_IN_CREATE 114
#define IDS_TOOLTIP_ALT_NAME            115
#define IDS_TOOLTIP_ALT_NUM             116
#define IDS_TOOLTIP_REFLECTED           117
#define IDS_TOOLTIP_ID                  118
#define IDS_TOOLTIP_CODE                119
#define IDS_TOOLTIP_RANGE               120
#define IDD_OPTIONSDLG                  129
#define IDD_DIALOG_HANDLER              201
#define IDC_STATIC_MESSAGE              202
#define IDD_FUNCTION_PROPPAGE           202
#define IDD_GENERAL_PROPPAGE            203
#define IDD_DIALOG_ID_HANDLER           207
#define IDD_DIALOG_ADD_FUNC             208
#define IDC_BUTTON_APPLY                208
#define IDD_DIALOG_ADD_FUNC_GLOBAL      209
#define IDB_BITMAP_LOGO                 209
#define IDI_ICON_MAIN                   214
#define IDC_COMBO_CLASSES               215
#define IDC_CHECK_STYLE                 217
#define IDB_BITMAP_MESSAGE              217
#define IDC_EDIT_ID                     218
#define IDB_BITMAP_DDX                  218
#define IDD_ADDSPECFUNCDLG              219
#define IDB_BITMAP_ICONS                221
#define IDC_CHECK_CODE                  223
#define IDI_ICON_CLOSE                  223
#define IDC_CHECK_ID                    224
#define IDI_ICON_OPEN                   224
#define IDC_CHECK_REFLECTED             225
#define IDC_EDIT_DEF                    226
#define IDI_ICON_MESSAGE                226
#define IDC_STATIC1                     227
#define IDC_RADIO1                      228
#define IDC_RADIO2                      229
#define IDC_RADIO3                      230
#define IDC_COMBO1                      231
#define IDC_CHECK1                      232
#define IDC_CHECK2                      233
#define IDC_CHECK3                      234
#define IDR_REGISTRY1                   234
#define IDR_ADDIN8                      234
#define IDS_TOOLTIP_INLINE              236
#define IDS_TOOLTIP_NEW_STYLE           237
#define IDS_TOOLTIP_FUNCTION_NAME       238
#define IDC_CHECK_INLINE                239
#define IDC_COMBO_DDX_TYPE              240
#define IDC_COMBO_MEMBER_TYPE           241
#define IDC_COMBO_ID                    242
#define IDC_EDIT_MEMBER                 243
#define IDC_RADIO_PUBLIC                244
#define IDC_RADIO_PROTECTED             245
#define IDC_RADIO_PRIVATE               246
#define IDC_RADIO_PLACE_WHOLE           247
#define IDC_RADIO_PLACE_H               248
#define IDC_RADIO_TYPE_ANOTHER          250
#define IDC_RADIO_TYPE_WTL              251
#define IDC_RADIO_TYPE_ATL              252
#define IDC_CHECK_ASK_AGAIN             253
#define IDC_STATIC_LOGO                 254
#define IDC_STATIC_NAME                 255
#define IDC_CHECK_ONLYDLG               256
#define IDC_EDIT_DEPENDENCES            257
#define IDC_CHECK_ATLMISC               258
#define IDC_COMBO_MESSAGEMAP            259
#define IDC_CHECK_FORWARD               260
#define IDC_CHECK_REFLECT               261
#define IDC_STATIC_COPYRIGHT            262
#define IDC_EDIT_ALTNUM                 263
#define IDC_EDIT_ALTNAME                264
#define IDC_CHECK_RANGE                 265
#define IDC_STATIC_RANGE_START          266
#define IDC_COMBO_END_ID                267
#define IDC_COMBO_FUNCTION              268
#define IDC_CHECK_CREATE                269
#define IDC_CHECK_DESTROY               270
#define IDC_CHECK_ADD_CREATE            271
#define IDC_CHECK_REMOVE_DESTROY        272
#define IDC_CHECK_PREFIX                273
#define IDC_EDIT_INITIALIZER            274
#define IDC_BUTTON_WINDOWS_TEXT_COLOR   275
#define IDC_BUTTON_WINDOWS_BACK_COLOR   276
#define IDC_STATIC_WINDOWS              278
#define IDC_BUTTON_COMMAND_TEXT_COLOR   279
#define IDC_BUTTON_COMMAND_BACK_COLOR   280
#define IDC_STATIC_NOTIFY               281
#define IDC_STATIC_COMMAND              282
#define IDC_BUTTON_NOTIFY_TEXT_COLOR    283
#define IDC_BUTTON_NOTIFY_BACK_COLOR    284
#define IDC_BUTTON_COLORS               285
#define IDC_BUTTON_RESET                286
#define IDC_BUTTON_EXPORT               287
#define IDC_BUTTON_IMPORT               288
#define IDC_STATIC_DONATE               291
#define IDC_CHECK_ALLOW_DIALOAG_IDLE    292
#define IDC_CHECK_SAVE_PAGE             293
#define IDC_COMBO_WTLVERSION            294
#define IDC_COMBO_RANGE                 296
#define IDC_COMBO_CODE                  297
#define IDC_CHECK_WINDOW                298
#define IDC_COMBO_WINDOW                299
#define IDC_COMBO_REFLECTTYPE           300
#define IDC_CHECK_REFLECT_EX            301
#define IDC_CHECK_DEF_HANDLER           302
#define IDC_BUTTON_REFLECT_TEXT_COLOR   303
#define IDC_BUTTON_REFLECT_BACK_COLOR   304
#define IDC_STATIC_REFLECT              305
#define IDC_STATIC_DESC                 306
#define IDC_CHECK_MISS_END_MAP          307
#define IDC_CHECK_SORT                  1001
#define IDS_STRING_MES_ADD_HANDLER      20000
#define IDS_STRING_MES_DEL_HANDLER      20001
#define IDS_STRING_MES_ADD_FUNC         20003
#define IDS_STRING_MES_DEL_FUNC         20004
#define IDS_STRING_MES_SPEC_FUNC        20005
#define IDS_STRING_MES_ADD_MAP          20006
#define IDS_STRING_MES_DEL_MAP          20007
#define IDS_STRING_DDX_ADD_VAR          20030
#define IDS_STRING_DDX_DEL_VAR          20031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         308
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
